#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


def load_latest_run(tenant_id: str) -> dict:
    path = Path(f"logs/tenants/{tenant_id}/revenue_leaks_runs.jsonl")
    if not path.exists():
        raise FileNotFoundError(f"No run history found for tenant '{tenant_id}' at {path}")

    rows = []
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            rows.append(json.loads(line))
        except Exception:
            continue

    if not rows:
        raise RuntimeError(f"Run history file exists but has no valid rows: {path}")

    rows.sort(key=lambda r: r.get("runTs", ""), reverse=True)
    return rows[0]


def to_markdown(run: dict) -> str:
    cards = run.get("summaryCards", {})
    top = run.get("topLeaks", [])

    lines = [
        f"# Investor Snapshot — Tenant {run.get('tenantId', 'unknown')}",
        "",
        f"- **Template:** {run.get('template', 'revenue_leaks_v1')}",
        f"- **Run Timestamp:** {run.get('runTs', 'n/a')}",
        f"- **Total Estimated Leak (USD):** {cards.get('totalEstimatedLeakUsd', 0)}",
        f"- **Signals Detected:** {cards.get('signalsDetected', 0)}",
        f"- **High Severity Count:** {cards.get('highSeverityCount', 0)}",
        f"- **Net Revenue (Window):** {cards.get('netRevenueWindow', 0)}",
        "",
        "## Top Leaks",
        "",
        "| Signal | Estimated Loss USD | Severity | Confidence |",
        "|---|---:|---|---:|",
    ]

    for leak in top[:10]:
        lines.append(
            f"| {leak.get('signal_id', 'n/a')} | {leak.get('estimated_loss_usd', 0)} | {leak.get('severity', 'n/a')} | {leak.get('confidence', 0)} |"
        )

    lines.append("")
    lines.append("_Generated by HE Revenue Leaks investor snapshot export script._")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Export investor snapshot JSON + markdown from latest run")
    ap.add_argument("--tenant-id", required=True)
    ap.add_argument("--out-dir", default="reports/investor_snapshots")
    args = ap.parse_args()

    run = load_latest_run(args.tenant_id)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    ts = (run.get("runTs") or "latest").replace(":", "").replace("-", "")
    json_path = out_dir / f"{args.tenant_id}_{ts}_snapshot.json"
    md_path = out_dir / f"{args.tenant_id}_{ts}_snapshot.md"

    json_path.write_text(json.dumps(run, ensure_ascii=False, indent=2), encoding="utf-8")
    md_path.write_text(to_markdown(run), encoding="utf-8")

    print(json.dumps({"json": str(json_path), "markdown": str(md_path)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
